//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTE.Web.Pages.SpecialSection {
    
    
    public partial class DocumentsDownload {
        
        /// <summary>
        /// dlEducation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList dlEducation;
        
        /// <summary>
        /// DocumentList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList DocumentList1;
        
        /// <summary>
        /// dlPlans control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList dlPlans;
        
        /// <summary>
        /// dlRules control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList dlRules;
        
        /// <summary>
        /// dlInstructions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList dlInstructions;
        
        /// <summary>
        /// dlThesises control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList dlThesises;
        
        /// <summary>
        /// dlReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList dlReports;
        
        /// <summary>
        /// dlPaidServices control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList dlPaidServices;
        
        /// <summary>
        /// dlRevisions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DDTE.Web.Controls.DocumentsList dlRevisions;
    }
}
