//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int AlbumId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FolderName { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
