//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffId { get; set; }
        public string Name { get; set; }
        public string PhotoUrl { get; set; }
        public string Position { get; set; }
        public string Qualification { get; set; }
        public string Degree { get; set; }
        public string Education { get; set; }
        public string Speciality { get; set; }
        public string QualificationCourses { get; set; }
        public string GeneralExperience { get; set; }
        public string EducationExperience { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
