//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionSchedule
    {
        public int UnionScheduleId { get; set; }
        public int UnionProgramId { get; set; }
        public string Year { get; set; }
        public string LessonDuration { get; set; }
        public string HoursDay { get; set; }
        public string HoursWeek { get; set; }
        public string HoursYear { get; set; }
        public string LessonsPerWeek { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual UnionProgram UnionProgram { get; set; }
    }
}
