//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionAchievement
    {
        public UnionAchievement()
        {
            this.UnionAchievementParticipants = new HashSet<UnionAchievementParticipant>();
        }
    
        public int UnionAchievementId { get; set; }
        public int UnionProgramId { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string Participant { get; set; }
        public string Result { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual UnionProgram UnionProgram { get; set; }
        public virtual ICollection<UnionAchievementParticipant> UnionAchievementParticipants { get; set; }
    }
}
