//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionAchievementParticipant
    {
        public int UnionAchievementParticipantId { get; set; }
        public int UnionAchievementId { get; set; }
        public string ParticipantName { get; set; }
        public string Result { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual UnionAchievement UnionAchievement { get; set; }
    }
}
